"""empty message

Revision ID: 7a3f269336c2
Revises: 8edd1347ab40
Create Date: 2024-08-14 09:03:40.417739

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7a3f269336c2"
down_revision = "8edd1347ab40"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("history_chats", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=True,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("history_chats", schema=None) as batch_op:
        batch_op.drop_column("created_at")

    # ### end Alembic commands ###
